GET http://127.0.0.1:4000/contacts

###


GET http://localhost:3000/contacts
Host: localhost
####


POST http://127.0.0.1:3000/contacts
Content-Type: application/json

{
    "id": 4,
    "name": "Azamat",
    "phone": "+79262857754"
}

###

PUT http://127.0.0.1:3000/contacts/4
Content-Type: application/json

{
    "id": 4,
    "name": "Azamat",
    "phone": "+7926255555"
}

###

PATCH http://127.0.0.1:3000/contacts/4
Content-Type: application/json

{
    "phone": "+7926255551"
}


###

DELETE http://127.0.0.1:3000/contacts/5
Content-Type: application/json


###

GET https://jsonplaceholder.typicode.com/todos
