# Generated by Django 4.0.1 on 2022-01-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fullname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
