# Generated by Django 4.0.1 on 2022-01-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_note_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='desc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
