# Generated by Django 4.0.1 on 2022-01-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_note_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='f1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
