# Generated by Django 4.0.1 on 2022-01-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_note_content_note_f1_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='f1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
